name: CI

on:
  push:
    branches: ["feature/**", "feat/**", "fix/**", "hotfix/**"]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  analysis:
    uses: ./.github/workflows/reusable/static-analysis.yml
    with:
      publish-pages: false
    secrets: inherit

  image:
    needs: analysis
    uses: ./.github/workflows/reusable/build-and-push.yml
    with:
      image-name: hello-world-app
      image-tag: ${{ github.sha }}
      publish-latest: false
    secrets: inherit