name: Deploy ECS

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      aws-region:
        required: true
        type: string
      role-to-assume:
        required: true
        type: string
      cluster:
        required: true
        type: string
      service:
        required: true
        type: string
      task-family:
        required: true
        type: string

jobs:
  deploy-to-ecs:
    runs-on: ubuntu-latest
    environment:
      name: production

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.role-to-assume }}
          aws-region: ${{ inputs.aws-region }}

      - name: Download active task definition
        run: |
          aws ecs describe-task-definition \
            --task-definition "${{ inputs.task-family }}" \
            --query taskDefinition \
            --output json > task-definition.json

      - name: Clean task definition
        run: |
          jq 'del(
            .taskDefinitionArn,
            .revision,
            .status,
            .requiresAttributes,
            .compatibilities,
            .registeredAt,
            .registeredBy
          )' task-definition.json > clean.json

      - name: Get container name
        id: container
        run: |
          echo "name=$(jq -r '.containerDefinitions[0].name' clean.json)" >> $GITHUB_OUTPUT

      - name: Render new task definition
        id: render
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: clean.json
          container-name: ${{ steps.container.outputs.name }}
          image: ${{ inputs.image }}

      - name: Deploy to Amazon ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.render.outputs.task-definition }}
          service: ${{ inputs.service }}
          cluster: ${{ inputs.cluster }}
          wait-for-service-stability: true
